### ISSUE TITLE
[Bug] The contract in 2-b does not implement correct interface

### ISSUE THREAD

**Issue by bossjoker1** [jcsec-security/all-things-reentrancy#1]
When I was doing <02_b Basic reentrancy with a twist>, I found that the interface defined in the Attacker Contract was not consistent with the Victim Contract. So I guess it might be a mistake.
As shown in the figure below, the Vulnerable_ERC4626 Contract does not implement this interface.
![D3O0WMND TMSQT{{`VHA)U](https://github.com/jcsec-security/all-things-reentrancy/assets/55970422/f67d6ae6-a9d9-4493-a0a2-90fbb77fd042)

**Comment by jf-li00** [comment]
I've opened a PR #2 to fix this

**Comment by Mortal-zz** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
gabrielstoica, @johnsaigle, @DhairyaSethi, @kuldeep23907, @magiconch, @gattacker, @owieth, @prashantnigam10, @Hack-Light, @aysha8665, @assaliant, @alebaffa, @Sachinart, @libaice, @Perelyn-sama, @kagzgenius, @stfibonacci, @stoneworld, @SWO2D, @rajatlko13

**Comment by jcsec-security** [comment]
You were correct! fixed this a while ago. Thanks!!
